### ISSUE TITLE
End-Effector Visualization for move group 'manipulator' wrongly placed

### ISSUE THREAD

**Issue by gollth** [ros-planning/panda_moveit_config#101]
## Details

If I want to plan with the `manipulator` move group and choose this in the RVIZ Motion Planning Plugin, the Interactive Marker Gizmo shows at the wrong link, namely at `panda_link8` with the 45° rotation:
![Screenshot from 2022-02-09 09-48-03](https://user-images.githubusercontent.com/31999281/153159514-83c8339b-e8cb-4b9a-99cf-de92c59aa41d.png)

## Expected Behaviour

The Gizmo shows in a way, that I can drag the EE around nicely:

![Screenshot from 2022-02-09 09-53-55](https://user-images.githubusercontent.com/31999281/153159943-fcc2499c-aa98-4c94-bdec-3b6ed4543a4c.png)

## Steps to Reproduce

```console
roslaunch panda_moveit_config demo.launch
```

and choose `manipulator` in RVIZ Motion Planning Plugin.

**Comment by rhaschke** [comment]
Fixed via c8950cc4cf68251e8959d6b6c7de221de2f4bdd9.
