### ISSUE TITLE
Installing this package in Noetic gets the Melodic release

### ISSUE THREAD

**Issue by karl-exwzd** [ros-planning/panda_moveit_config#103]
When installing the package `ros-noetic-panda-moveit-config` the Melodic release is installed, which is not compatible with the Noetic version of `franka_description` which is one of its dependencies.

The error is following:

    Param xml is <param if="$(eval arg('load_robot_description') and arg('load_gripper'))" name="$(arg robot_description)" command="$(find xacro)/xacro '$(find franka_description)/robots/panda_arm_hand.urdf.xacro'"/>

That's because in the [Noetic](https://github.com/ros-planning/panda_moveit_config/blob/noetic-devel/launch/planning_context.launch#L13) branch the robot description with and without the gripper has been merged compared to [Melodic](https://github.com/ros-planning/panda_moveit_config/blob/melodic-devel/launch/planning_context.launch#L14-L15).

How come one gets the Melodic release in ROS Noetic?

**Comment by rhaschke** [comment]
The noetic-devel branch is work in progress. It was not yet released. See #96 for some details.

**Comment by karl-exwzd** [comment]
@rhaschke Thank you for the information.

I was very confused when installing a package on which the dependency was broken in this particular way. I'll wait then.

I guess this ticket can be closed for now?
