### ISSUE TITLE
ROS Noetic Version Broken in Apt

### ISSUE THREAD

**Issue by fishbotics** [ros-planning/panda_moveit_config#111]
When I install this on 20.04 using `sudo apt install ros-noetic-franka-ros ros-noetic-franka-description` and try launching with `roslaunch panda_moveit_config demo.launch`, I get an error saying 
`No such file or directory: /opt/ros/noetic/share/franka_description/robots/panda_arm_hand.urdf.xacro`. 

From what I found online, this is due an error in this launch file: ` /opt/ros/noetic/share/panda_moveit_config/launch/planning_context.launch` and how it shouldn't load a separate URDF for the hand anymore. From what I can tell, the code is already fixed in the `noetic-devel` branch. I think this just needs to be updated in `apt` and it should work.

**Comment by rhaschke** [comment]
Should be fixed with upcoming release 0.8.
