### ISSUE TITLE
How do we set the end_effector_link and pose_reference_frame from within the launch file?

### ISSUE THREAD

**Issue by rpapallas** [ros-planning/panda_moveit_config#114]
While working with Panda and MoveIt (using our custom launch files, based on the `panda_moveit_config` ones), we realised that in our scripts we have to set the following two lines to "tell" MoveIt the appropriate reference frame and end-effector link:

```
moveit_group.set_end_effector_link("panda_hand_tcp")
moveit_group.set_pose_reference_frame("panda_link0")
```

Although this solves the problem, we want to move this into the `move_group.launch` launch file. Is there any way we could set those two values through the launch file?

Thank you in advance.

**Comment by rhaschke** [comment]
There is no option to set those group-dependent parameters via the launch file.

> moveit_group.set_end_effector_link("panda_hand_tcp")

The end-effector link defaults to the [last link in a chain](https://github.com/ros-planning/moveit/blob/605b28aaf4fe573000f3e4995c36c66d143e3885/moveit_ros/planning_interface/move_group_interface/src/move_group_interface.cpp#L139-L140). Thus, just define your `group` correspondingly, which should already be the case for both groups, panda_arm and panda_manipulator.

> moveit_group.set_pose_reference_frame("panda_link0")

The pose reference frame defaults to the [robot's root frame](https://github.com/ros-planning/moveit/blob/605b28aaf4fe573000f3e4995c36c66d143e3885/moveit_ros/planning_interface/move_group_interface/src/move_group_interface.cpp#L141).

**Comment by rpapallas** [comment]
Thank you, @rhaschke, for getting back to me. Just to confirm, there is no way we could set these even from a YAML or other config file? They are kind of implicitly defined through the model?

**Comment by rhaschke** [comment]
Yes, the defaults are defined by the SRDF essentially.

**Comment by rpapallas** [comment]
Thank you, @rhaschke.
