### ISSUE TITLE
  How to obtain the pressure of the real Franka's end effector (not gripper) and control it to generate a constant force (such as 0.5kg)? 

### ISSUE THREAD

**Issue by Franka-Med** [ros-planning/panda_moveit_config#117]
From the command line:
`rostopic echo / joint_ states`
I can obtain the torque of each joint. 
Further, I want to obtain the pressure of the end effector (not the grasping force of the claw) and control the robot arm based on the torque. May I ask if this idea can be implemented in moveit? If so, what should I do? Thank you very much.

**Comment by rhaschke** [comment]
You should ask this over at https://github.com/frankaemika/franka_ros
