### ISSUE TITLE
collision problem from start the panda moveit demo.launch in noetic version

### ISSUE THREAD

**Issue by cnaes93** [ros-planning/panda_moveit_config#118]
Hi
I installed recently the moveit for noetic from [link](https://ros-planning.github.io/moveit_tutorials/doc/getting_started/getting_started.html) and clone the panda-moveit.config the melodic version (-b melodic-devel) like in the Installation was. But when I launch it 
`roslaunch panda_moveit_config demo.launch rviz_tutorial:=true`
 from the start the panda robot is in collision state I think (the links are red) like in the picture.
![image](https://user-images.githubusercontent.com/108675000/185575399-89085e6a-0142-41f5-9f2d-63574a234974.png)

Then I reinstalled it this time with (-b noetic-devel). It didn't solved the Problem. 
 After that i tried to do a motion planning but I got the error:
**Panda-arm:Motion planning start tree could not be initialized**

How can I solve this issue?

**Comment by rhaschke** [comment]
The melodic-devel branch of panda_moveit_config is known to have collision issues. However, this was solved (but not yet released) in Noetic. Hence, running the most recent code (of MoveIt@master and panda_moveit_config@noetic-devel) this works for me:
![image](https://user-images.githubusercontent.com/5376030/185589904-27ab5159-8f3b-4753-ac9f-1e80bc3049ff.png)

Could you please check/specify the exact versions of MoveIt and panda_moveit_config you use?
Given that your group is called hand (instead of panda_hand), I suspect that you are using old versions.

**Comment by cnaes93** [comment]
How can I find the version of moveit and panda_moveit_config?
for the panda_moveit_config I used: [link](https://github.com/ros-planning/panda_moveit_config)

and for [moveit:](https://raw.githubusercontent.com/ros-planning/moveit/master/moveit.rosinstall)


as in the installation mentioned.

**Comment by rhaschke** [comment]
> How can I find the version?

https://unix.stackexchange.com/questions/6284/how-do-i-check-package-version-using-apt-get-aptitude
https://stackoverflow.com/questions/949314/how-do-i-get-the-hash-for-the-current-commit-in-git

**Comment by cnaes93** [comment]
I solved it. I started the installing  from [Getting Started ](https://ros-planning.github.io/moveit_tutorials/doc/getting_started/getting_started.html) and there is no `sudo apt install ros-noetic-moveit`
so i actually didn't installed the moveit, but I'm wondering how could I opend the moveit without installing it. How ever I find my problem after I compared the installings code between Melodic and Notic version. There is no sudo apt install ros-notic-moveit in noetic version (it's in first page of moveit, not in getting started).

**Comment by rhaschke** [comment]
The Noetic version of Getting Started installs MoveIt from source as explained [here](https://ros-planning.github.io/moveit_tutorials/doc/getting_started/getting_started.html#create-a-catkin-workspace-and-download-moveit-source). But even without this step, the required packages should get installed via rosdep as explained [here](https://ros-planning.github.io/moveit_tutorials/doc/getting_started/getting_started.html#build-your-catkin-workspace).

**Comment by cnaes93** [comment]
I did the installation via rosdep as explained there on 2 devices but there was no Panda_hand in MotionPlanning (just hand) and collision problem for start planning the robot (Panda-arm:Motion planning start tree could not be initialized). So reinstalled moveit again this time with  `sudo apt install ros-noetic-moveit` and then installing the packages and finally evrythings work well.
