### ISSUE TITLE
where is panda.srdf?

### ISSUE THREAD

**Issue by ZhangShuaiGou** [ros-planning/panda_moveit_config#12]
Hi, I am learning the tutorial-Visualizing Collisions.
When I run "roslaunch moveit_tutorials visualizing_collisions_tutorial.launch", it will come out with ERROR:ioerror: [errno 2] no such file or directory: 'myubuntu/catkin_ws/src/panda_moveit_config/config/panda.srdf'.
Then I go through the .launch file, find the code below:
  ```
<!-- load SRDF -->
  <param name="robot_description_semantic" textfile="$(find panda_moveit_config)/config/panda.srdf" />
```

It seems like there is no panda.srdf in the /panda_moveit_config/config in this repository and this package.
What can I do to fix it? Thanks in advance!

**Comment by davetcoleman** [comment]
This needs to be modified to use xacro, similar to https://github.com/frankaemika/franka_ros/blob/6eb8b67dd0a4d9d5af514070f02efae711c2f67f/panda_moveit_config/launch/planning_context.launch

However it might make sense to just load the planning_context.launch instead of duplicating this in every launch file. @mlautman thoughts?

**Comment by ZhangShuaiGou** [comment]
> This needs to be modified to use xacro, similar to https://github.com/frankaemika/franka_ros/blob/6eb8b67dd0a4d9d5af514070f02efae711c2f67f/panda_moveit_config/launch/planning_context.launch
> 
> However it might make sense to just load the planning_context.launch instead of duplicating this in every launch file. @mlautman thoughts?

Thanks for your reply! I am gonna close it!

**Comment by aPonza** [comment]
FYI this affects also the setup assistant, which can't find file panda.srdf when loading panda_moveit_config
