### ISSUE TITLE
No such file or directory:

### ISSUE THREAD

**Issue by YXGuan** [ros-planning/panda_moveit_config#120]
Hi there, 

I update my local [panda_moveit_config](https://github.com/ros-planning/panda_moveit_config) repo today and received the following error message: 

![image](https://user-images.githubusercontent.com/55643200/189536506-797af074-981d-4ff6-a7b7-66ecdef68d2b.png)

**Comment by rhaschke** [comment]
Please also update `franka_description`! It's released but not yet synced.

**Comment by YXGuan** [comment]
I see. Thank you sir

**Comment by YXGuan** [comment]
@rhaschke  
Hi Dr. Haschke, 

Sorry I have a question unrelated to this issue:
When I was attempting to add a griper in Define Planning Groups in MoveIt Setup Assistant, I can't see any available links related to panda_hand, panda_leftfinger, and panda_rightfinger. Did I do something stupid or am I using the wrong URDF file?

Thanks, 

![image](https://user-images.githubusercontent.com/55643200/189566134-79bd5aca-bdef-48aa-9519-3d2de94ff68e.png)

![image](https://user-images.githubusercontent.com/55643200/189566389-9e84e697-238c-4926-8720-8d2f2decbfc0.png)

**Comment by rhaschke** [comment]
In order to get a gripper, you need to pass xacro arguments: `hand:=true`

**Comment by YXGuan** [comment]
Thank you very much
