### ISSUE TITLE
strange self-collision

### ISSUE THREAD

**Issue by marcbone** [ros-planning/panda_moveit_config#121]
When running demo.launch there is a red visualization indicating a self-collision: 
![image](https://user-images.githubusercontent.com/16033059/189596614-47dec6c1-56ba-40ba-b1b6-f02eb8a581c8.png)
I am not sure what that means as planning still works. Also looking at the srdf, I do not see why these collisions are enabled, as there is a "disable_default_collisions" for panda_link4_sc. I found 3 different methods to solve this. You can either add:

* `<disable_collisions link1="panda_link3_sc" link2="panda_link4_sc" reason="Never"/>`,
* `<disable_collisions link1="panda_link4_sc" link2="panda_link4" reason="Never"/>`
* or `<disable_collisions link1="panda_link4_sc" link2="panda_link3" reason="Never"/>`

to the srdf.

Looking at the status message, I would guess that you would need both of the last 2 options for this to work, but you only require one of the 3 options. So I am a bit puzzled on what is going on.

I was using the noetic-devel branch for this

**Comment by rhaschke** [comment]
You need to build MoveIt from source as we didn't yet release the most recent changes to get the new ACM working.
This is on my TODO list though.
