### ISSUE TITLE
Does /franka_control/set_EE_frame service change the end effector of current move group ?   

### ISSUE THREAD

**Issue by Assets01** [ros-planning/panda_moveit_config#122]
Using /franka_control/set_EE_frame service can set NE_T_EE, thus changes 'panda_ee' frame in TF tree. I wonder when using moveit for planning after set_EE_frame, what happens to the defined end effector?

 e.g., when using panda_manipulator move group, the default end effector is 'pand_hand_tcp', and 'panda_ee' frame is equal to 'pand_hand_tcp' frame, the planed cartesian path is for 'pand_hand_tcp', right?  but after using set_EE_frame, the 'panda_ee' frame is changed, then the planned path is for the changed 'panda_ee' or still for  'pand_hand_tcp'?

**Comment by AndyZe** [comment]
That service sounds like something that's unique to the Panda. Unfortunately MoveIt doesn't know anything about it so I expect the MoveIt planning frame wouldn't change.

If you're using the MoveGroupInterface (C++), you can change the planning frame with `setEndEffectorLink()`:  

https://github.com/ros-planning/moveit/blob/327b5b09cc48b97ba3f2a9ac2acf1edcd1bb0650/moveit_ros/planning_interface/move_group_interface/include/moveit/move_group_interface/move_group_interface.h#L650
