### ISSUE TITLE
rotating the gripper

### ISSUE THREAD

**Issue by cnaes93** [ros-planning/panda_moveit_config#126]
I have some Objects on the table that Robot must pick them up in certain direction.  My idea was to rotate the robot's joint 6 to grab them. But I realized that joint 6 has a limitation and couldn't rotate in 360 degrees.  I printed new gripper and changed fingers of the robot so gripper must  be able to rotate 360 to grab the object.
Then I tried using the quaternion to set the appropriate pose for the robot to grab the object, but I have no idea how it works.
My question is what is the best method to just rotating the gripper;  Using  pose_goal.orientation (quaternion) or changing the limitation of joint 6 (joint_goal[6]) or is there a better solution?
Tanks in advance

**Comment by rhaschke** [comment]
This question should be better asked at https://answers.ros.org. Please, post real issues and bug reports here only.
You can't change the joint limits - these are defined by hardware limits. So, specify the correct orientation via a quaternion...
