### ISSUE TITLE
no panda_moveit_config.launch

### ISSUE THREAD

**Issue by zehub123** [ros-planning/panda_moveit_config#127]
no panda_moveit_config.launch? which file has the same function in the new respsitory? Thank you very much.

**Comment by rhaschke** [comment]
There was never a file like `panda_moveit_config.launch`. Probably you mean:
`roslaunch panda_moveit_config demo.launch`
or
`roslaunch panda_moveit_config move_group.launch`

**Comment by zehub123** [comment]
thanks,  can I use franka_control. launch replace panda_moveit_config.launch?

**Comment by rhaschke** [comment]
If you want to run the real robot:
`roslaunch panda_moveit_config franka_control.launch`
