### ISSUE TITLE
 remove `groud_plane` in gazebo

### ISSUE THREAD

**Issue by chauvinSimon** [ros-planning/panda_moveit_config#128]
By default, [`roslaunch panda_moveit_config demo_gazebo.launch`](https://github.com/ros-planning/panda_moveit_config/blob/noetic-devel/launch/demo_gazebo.launch) populates `Models` with two objects:
- the panda
- a `ground_plane`

Internally, `demo_gazebo.launch` launches [`franka_gazebo/launch/panda.launch`](https://github.com/frankaemika/franka_ros/blob/develop/franka_gazebo/launch/panda.launch) from `franka_gazebo`

As shown on the animation, the `ground_plane` acts as an obstacle and prevents the robot from reaching negative `z`

![gazebo_ground_plane](https://user-images.githubusercontent.com/34301767/208127743-253fa002-d48b-41c9-9e2a-61841cc7a09b.gif)

A solution is to **manually remove `ground_plane`, but this needs to be done each time gazebo is started**

My question: **is it possible to remove `ground_plane` permanently?**

I guess it must be **defined in some config file**
- Nevertheless **I could not find where**
- In [`stone.sdf`](https://github.com/frankaemika/franka_ros/blob/develop/franka_gazebo/world/stone.sdf), removing the section of `<uri>model://ground_plane</uri>` does not help.

**Comment by rhaschke** [comment]
Loading `franka_gazebo/panda.launch` allows to specify your own Gazebo world model: https://github.com/rhaschke/franka_ros/blob/cartesian-impedance/franka_gazebo/launch/panda.launch#L8

Specifying `stone.sdf` with groundplane removed, works as expected:
`roslaunch franka_gazebo panda.launch world:=$PWD/src/robots/franka_ros/franka_gazebo/world/stone.sdf x:=-1`
![image](https://user-images.githubusercontent.com/5376030/208236848-e306a1f2-580d-4398-92ae-41d4595cff0c.png)

The default world, Gazebo's `/usr/share/gazebo-11/worlds/empty.world` comprises the ground plane as well.

**Comment by chauvinSimon** [comment]
Brilliant!
Thank you @rhaschke for the quick and complete answer!
