### ISSUE TITLE
*Bug* on fake and simple controllers  controllers

### ISSUE THREAD

**Issue by rafaelrojasmiliani** [ros-planning/panda_moveit_config#129]
`roslaunch`can fail when loading parameters for simple and fake controllers [here](https://github.com/ros-planning/panda_moveit_config/blob/b5ce35571832b4165f67f5db51c69581354d2cee/launch/simple_moveit_controller_manager.launch.xml#L6) and [here](https://github.com/ros-planning/panda_moveit_config/blob/b5ce35571832b4165f67f5db51c69581354d2cee/launch/fake_moveit_controller_manager.launch.xml#L10) respectively, the command does not substitute the `arm_id` variable because `<arg name="arm_id" default="panda" />` is missing in the corresponding launch files.

**Comment by rhaschke** [comment]
These files are included from [move_group.launch](https://github.com/ros-planning/panda_moveit_config/blob/b5ce35571832b4165f67f5db51c69581354d2cee/launch/move_group.launch#L84) via [trajectory_execution.launch.xml](https://github.com/ros-planning/panda_moveit_config/blob/b5ce35571832b4165f67f5db51c69581354d2cee/launch/trajectory_execution.launch.xml#L21), both times using `pass_all_args="true"`. Thus arm_id (and other args) are inherited from move_group.launch.
You should not launch those files directly.
