### ISSUE TITLE
Release into Lunar?

### ISSUE THREAD

**Issue by rhaschke** [ros-planning/panda_moveit_config#13]
Dear @davetcoleman,
Currently our Lunar Docker containers fail to build, because panda_moveit_config is not yet released into Lunar:
https://hub.docker.com/r/moveit/moveit/builds/bt27uxgqr446z6wwz6uywpn/

I think we should prepare a Lunar release as well. Do you agree?
However, first somebody should fix #12. Not sure what process generates the .srdf from .srdf.xacro...

**Comment by davetcoleman** [comment]
Makes sense to me. @fwalch ?

We could also remove Lunar from Docker, I don't think we need to make anymore releases of that OS

**Comment by rhaschke** [comment]
This needs a release of `franka_description` first.

**Comment by fwalch** [comment]
We can easily release `franka_description`, but I'm not sure about the actual control parts (libfranka etc), as we don't use Lunar (and Yakkety/Zesty). Also Lunar will hit EOL in May already.

It could still make sense to release this for Lunar anyway, even without libfranka - you can use `demo.launch` and, with the new setup assistant, generate a URDF for Gazebo.

What do you think?

**Comment by rhaschke** [comment]
Yes, you did the same for Melodic: Please only release franka_description if you feel more comfortable with this. However, we do have a Lunar release of MoveIt and thus should also provide `moveit_tutorials`, and thus `panda_moveit_config`...

**Comment by fwalch** [comment]
> Yes, you did the same for Melodic: Please only release franka_description if you feel more comfortable with this

Alright, I just wanted to clarify. For Melodic, we will release `libfranka` etc as well.

**Comment by fwalch** [comment]
Opened https://github.com/ros/rosdistro/pull/19497

**Comment by davetcoleman** [comment]
Docker images have just been removed for Lunar fyi
