### ISSUE TITLE
Run stomp planner error "The 'stomp' configuration parameter was not found"

### ISSUE THREAD

**Issue by hlhfhmt** [ros-planning/panda_moveit_config#131]
I install moveit and stomp planner from source in Ubuntu 20. When i run the demo for the stomp planner with the command "roslaunch panda_moveit_config demo_stomp.launch ", i get the following error:
`[ERROR] [1674098279.924124491]: The 'stomp' configuration parameter was not found
terminate called after throwing an instance of 'std::runtime_error'
  what():  Unable to initialize planning plugin
[move_group-5] process has died [pid 3939941, exit code -6, cmd /home/dell/ws_moveit/devel/lib/moveit_ros_move_group/move_group --debug __name:=move_group __log:=/home/dell/.ros/log/df160252-97a7-11ed-b47c-ebb3863f028e/move_group-5.log].
log file: /home/dell/.ros/log/df160252-97a7-11ed-b47c-ebb3863f028e/move_group-5*.log
[ INFO] [1674098280.451824028]: Stereo is NOT SUPPORTED
[ INFO] [1674098280.451920599]: OpenGL device: NVIDIA GeForce RTX 3090/PCIe/SSE2
[ INFO] [1674098280.451941955]: OpenGl version: 4.6 (GLSL 4.6).
[ INFO] [1674098283.856437647]: Loading robot model 'panda'...
[ INFO] [1674098283.959639331]: Starting planning scene monitor
[ INFO] [1674098283.961705455]: Listening to '/move_group/monitored_planning_scene'
[ INFO] [1674098284.367928116]: waitForService: Service [/get_planning_scene] has not been advertised, waiting...
[ INFO] [1674098289.374384433]: Failed to call service get_planning_scene, have you launched move_group or called psm.providePlanningSceneService()?
[ INFO] [1674098289.374592777]: Constructing new MoveGroup connection for group 'panda_arm' in namespace ''
[ERROR] [1674098319.388580579]: Unable to connect to move_group action server 'move_group' within allotted time (30s)
[ INFO] [1674098319.389808524]: Constructing new MoveGroup connection for group 'panda_arm' in namespace ''
[ERROR] [1674098349.402577899]: Unable to connect to move_group action server 'move_group' within allotted time (30s)
`
All planner config are right, any solutions to deal with that?

**Comment by ChuGuoqing** [comment]
I got the same error. Have you solved the problem?

**Comment by new2me321** [comment]
I am also facing the same error. Did anyone find the solution?

**Comment by new2me321** [comment]
Hello, I found a solution to the issue. 
There is no need to define the planning group name in the file "stomp_planning_pipeline.launch.xml".  
~~group ns="$(arg arm_id)_arm"~~

Just delete all the lines with the "group"  tag in that file and replace them with 
`<rosparam command="load" file="$(find panda_moveit_config)/config/stomp_planning.yaml"/>`
![Screenshot from 2023-06-08 13-48-30](https://github.com/ros-planning/panda_moveit_config/assets/70843576/ea939011-10da-4d56-a838-846dfcfe778d)

However, you need to define the planning group directly in the 'stomp_planning.yaml' file

`stomp/panda_arm:`
`  group_name: panda_arm`
`  optimization:`
`    num_timesteps: 60`
`    num_iterations: 40`
   ` ...`

**Comment by ChuGuoqing** [comment]
excellent work！！ Thank you very much&nbsp;


824738078
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年6月8日(星期四) 晚上6:52
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ros-planning/panda_moveit_config] Run stomp planner error &quot;The &#39;stomp&#39; configuration parameter was not found&quot; (Issue #131)





 
Hello, I found a solution to the issue.
 There is no need to define the planning group name in the file "stomp_planning_pipeline.launch.xml".
 group ns="$(arg arm_id)_arm"
 
Just delete all the lines with the "group"  tag in that file and replace them with
 <rosparam command="load" file="$(find panda_moveit_config)/config/stomp_planning.yaml"/&gt;
 
 
However, you need to define the planning group directly in the 'stomp_planning.yaml' file
 
stomp/panda_arm:
   group_name: panda_arm
   optimization:
     num_timesteps: 60
     num_iterations: 40
  ...

**Comment by Joinjiang** [comment]
but, it still have a another the same error show up? how to solve it

**Comment by ravijo** [comment]
Thank you very much. I submitted the following pull request based on this thread.
https://github.com/ros-planning/panda_moveit_config/pull/137

The changes can be seen on the following commit:
https://github.com/ravijo/panda_moveit_config/commit/9a02d4df0ba97c9df5d1e06d490d053f02ff6229

**Comment by ravijo** [comment]
@Joinjiang 

Until the pull request is approved and merged, you can pull the changes from the following repository:
https://github.com/ravijo/panda_moveit_config

**Comment by ravijo** [comment]
As for future readers, the latest commit https://github.com/ros-planning/panda_moveit_config/commit/058a848abef4e527b25b89f9d3d13ce716855bd8 by @rhaschke, proposes a much cleaner and better solution. Please use the [official repository](https://github.com/ros-planning/panda_moveit_config).
