### ISSUE TITLE
unify kinetic and melodic into master branch

### ISSUE THREAD

**Issue by rhaschke** [ros-planning/panda_moveit_config#25]
Kinetic and Melodic branches for this repo have diverged for no reason. Usually, there is no reason to distinguish ROS distros for a moveit_config package.

The latest kinetic release is missing several commits compared to melodic, which is the cause for several issues, e.g. https://github.com/ros-planning/moveit/issues/1426 and #17.

I suggest to continue development on a master branch only, i.e. drop `kinetic-devel` and rename `melodic-devel` to `master`.

![diverged](https://user-images.githubusercontent.com/5376030/55615724-6d2bb980-5790-11e9-9090-513baaf3671f.png)

**Comment by rhaschke** [comment]
@davetcoleman or @mlautman, could you please comment on this suggestion and then take the appropriate actions?

**Comment by rhaschke** [comment]
In view of #31, which introduces an actual deviation between kinetic and melodic, I suggest
1. to _hard-reset_ `kinetic-devel` (which currently has two randomly chosen cherry-picks from melodic-devel) to `melodic-devel`
2. release those changes into both, kinetic and melodic (maybe also including #30)
3. and _subsequently_ branch off melodic-devel from kinetic-devel to handle #31.

**Comment by mlautman** [comment]
Sounds like a good plan

**Comment by rhaschke** [comment]
Done. Releases triggered:
* for Melodic: https://github.com/ros/rosdistro/pull/21451
(Not sure, why  @mlautman didn't release 0.7.2 when he created the release tag)
* for Kinetic: https://github.com/ros/rosdistro/pull/21450
