### ISSUE TITLE
No joint state information if virtual joint is set to floating

### ISSUE THREAD

**Issue by ommmid** [ros-planning/panda_moveit_config#38]
If the virtual joint in panda_arm.xacro is set to floating, then haveCompletedState() from StateMonitor never returns true Indicating we have no joint state information for at least one joint. I saw similar issues (#33 ) but they are in kinetic, I am running melodic

**Comment by davetcoleman** [comment]
See my rationale for why I like having a floating joint, but a workaround for it instead:
https://github.com/ros-planning/moveit_msgs/pull/55

**Comment by rhaschke** [comment]
Fixed via https://github.com/ros-planning/moveit_tutorials/pull/387.
