### ISSUE TITLE
where is demo_stomp.launch

### ISSUE THREAD

**Issue by mpatalberta** [ros-planning/panda_moveit_config#44]
The documentation talks about demo_stomp.launch.
If you have one could you please check it in.

**Comment by JEDV10** [comment]
If you open 'demo_chomp.launch', it is quite easy to generate your own 'demo_stomp.launch'. Just copy-paste 'demo_chomp.launch', rename it to 'demo_stomp.launch' and change the value of the argument "pipeline" from "chomp" to "stomp". It works for me.

**Comment by rickstaa** [comment]
@mpatalberta fixed when https://github.com/ros-planning/panda_moveit_config/pull/82 is merged.
