### ISSUE TITLE
The order of planning_adapters in moveit planner pipeline

### ISSUE THREAD

**Issue by jsbyysheng** [ros-planning/panda_moveit_config#56]
The `planning_adapters` of `ompl_planning_pipeline.launch.xml` in [panda_moveit_config(kinetic-devel)](https://github.com/ros-planning/panda_moveit_config/blob/kinetic-devel/launch/ompl_planning_pipeline.launch.xml) is the order of the following:

```
default_planner_request_adapters/AddTimeParameterization
default_planner_request_adapters/FixWorkspaceBounds
default_planner_request_adapters/FixStartStateBounds
default_planner_request_adapters/FixStartStateCollision
default_planner_request_adapters/FixStartStatePathConstraints
```

However,  The `planning_adapters` of `ompl_planning_pipeline.launch.xml` in [panda_moveit_config(melodic-devel)](https://github.com/ros-planning/panda_moveit_config/blob/melodic-devel/launch/ompl_planning_pipeline.launch.xml) is the order of the following:

```
default_planner_request_adapters/FixWorkspaceBounds
default_planner_request_adapters/FixStartStateBounds
default_planner_request_adapters/FixStartStateCollision
default_planner_request_adapters/FixStartStatePathConstraints
default_planner_request_adapters/ResolveConstraintFrames
default_planner_request_adapters/AddTimeParameterization"
```

I am very confused about why `default_planner_request_adapters/AddTimeParameterization` changes the order in `planning_adapters` ? Is that a bug ?

**Comment by rhaschke** [comment]
No, actually it works both ways around because the adapters choose themselves whether to run before or after the actual planner.
