### ISSUE TITLE
[bug] stomp_planning_pipeline.launch.xml should contain default_planner_request_adapters/AddTimeParameterization

### ISSUE THREAD

**Issue by jsbyysheng** [ros-planning/panda_moveit_config#58]
In [stomp_planning_pipeline.launch.xml](https://github.com/ros-planning/panda_moveit_config/blob/melodic-devel/launch/stomp_planning_pipeline.launch.xml), the `planning_adapters` should contain `default_planner_request_adapters/AddTimeParameterization` according to the [tutorial](https://ros-planning.github.io/moveit_tutorials/doc/stomp_planner/stomp_planner_tutorial.html#using-stomp-with-your-robot). Actually, it doesn't.

**Comment by rhaschke** [comment]
That's a bug. Please file a PR.

**Comment by jsbyysheng** [comment]
> That's a bug. Please file a PR.

ok

**Comment by tylerjw** [comment]
This was fixed with #59
