### ISSUE TITLE
planning_context confusion

### ISSUE THREAD

**Issue by swinterbotix** [ros-planning/panda_moveit_config#65]
Hi,

On line 24 of the [demo.launch](https://github.com/ros-planning/panda_moveit_config/blob/melodic-devel/launch/demo.launch#L24) file, the planning_context.launch file is included.

Later, on line 42 of the demo.launch file, move_group.launch is included (which is expected). Afterwards, the move_group.[launch file](https://github.com/ros-planning/panda_moveit_config/blob/melodic-devel/launch/move_group.launch#L5) then includes the planning_context.launch file again?!?!?!?

Why is this file being included twice in the same pipeline? I did some poking around, and it seems like the MoveIt Setup Assistant Wizard also generates files this way?

**Comment by rhaschke** [comment]
Thanks for pointing this out. But the double inclusion is for a reason:
The first inclusion in `demo.launch` uses the argument `load_robot_description=true` to ensure that URDF and SRDF are loaded.
The second inclusion in move_group.launch doesn't use this argument. It relies on these parameters to be loaded in advance - typically by some `bringup.launch` of a robot.
As `planning_context.launch` just loads some parameters, there is no harm to include it twice.
