### ISSUE TITLE
Add documentation for creating this package.

### ISSUE THREAD

**Issue by tylerjw** [ros-planning/panda_moveit_config#73]
I recognize that much of what is needed to create this package is documented in the tutorials:
https://ros-planning.github.io/moveit_tutorials/doc/setup_assistant/setup_assistant_tutorial.html

However, there are missing steps in the tutorial to exactly reproduce this repo (default poses for example).  Those things should either be documented in the readme for this package or in the tutorials.  As the tutorials is more of an example for others on how to setup their robot it shouldn't have to include specifics like the default poses in this package.

**Comment by rhaschke** [comment]
There is no need to document how to exactly reproduce all the robot poses of this package. The package is provided as is.
However, I agree that the tutorials should document how poses can be defined in general and it already does:
https://ros-planning.github.io/moveit_tutorials/doc/setup_assistant/setup_assistant_tutorial.html#step-5-add-robot-poses
