### ISSUE TITLE
Melodic-devel release

### ISSUE THREAD

**Issue by sgabl** [ros-planning/panda_moveit_config#75]
Hi, we just [released](https://github.com/ros/rosdistro/pull/27097) `franka_ros 0.7.1`. Can you please release the `melodic-devel` branch?

**Comment by rickstaa** [comment]
@rhaschke I think we can close this issue.

**Comment by rhaschke** [comment]
We will trigger a new release as soon as all open issues in #89 are fixed on `franka-ros` side, primarily https://github.com/frankaemika/franka_ros/pull/188.

**Comment by rhaschke** [comment]
We should keep this open until we actually triggered the release.

**Comment by rhaschke** [comment]
I triggered a new Melodic release: https://github.com/ros/rosdistro/pull/34182
