### ISSUE TITLE
Release 0.7.x for Noetic

### ISSUE THREAD

**Issue by fwalch** [ros-planning/panda_moveit_config#77]
As #72 seems to require additional work, would it be possible to release the existing `melodic-devel` branch for Noetic? I only performed basic tests, but it seems to work without issues on Noetic. Our `franka_example_controllers` package depends on `panda_moveit_config`, so we cannot publish it to the ROS repos unless `panda_moveit_config` is in there as well.

**Comment by tylerjw** [comment]
I assigned this to myself and will work on getting this done.

**Comment by tylerjw** [comment]
https://github.com/ros/rosdistro/pull/28831

**Comment by fwalch** [comment]
Thank you! However, the 0.7.4 tag is outdated compared to `melodic-devel`, and I think there will be problems with the `franka_ros` version already in the Noetic repos. I was hoping you could create a new release tag from the current `melodic-devel` branch head. Sorry for not being clear.

Related for Melodic: #75

**Comment by tylerjw** [comment]
Oh, I'm sorry I misunderstood.  I can cut a release of the latest for noetic.

**Comment by tylerjw** [comment]
https://github.com/ros/rosdistro/pull/28851

**Comment by tylerjw** [comment]
It was merged into rosdistro.  This will go out in the next sync.  I hope that fixes your issue.

**Comment by fwalch** [comment]
It does, thank you!

**Comment by rickstaa** [comment]
@tylerjw Thanks a lot for this release!
